/**
 * This package contains classes for the user interface.
 * Each class creates specific parts of the GUI, and
 * each contain various methods that allow for adjusting those aspects.
 * The UI itself is broken down into multiple components: The MainFrame which holds the layout of the buttons and labels that surround the
 * chart. The chart itself, which is instantiated within the {@code GUI} class, highlights the current benchmark
 * This package is Swing dependant, meaning that it runs on Swing and will not work without the Swing Library.
 * The {@code DiskWorker} class is dependent on the {@code GUI} class in this package. DiskWorker sends the current data for a specific block
 * to the GUI class to plot it on the chart
 * The {@code GUI} class is generated in the {@code App} class, and the {@code App} class too, is coupled with {@code GUI} class and
 * the {@code MainFrame} class.
 * The {@code MainFrame} is dependent and generated by the {@code GUI}
 *
 */
package edu.touro.mco152.bm.ui;